version: 2

sources:
  - name: tpch
    database: samples
    schema: tpch  
    tables:
      - name: orders
      - name: customer

  - name: nyctaxi
    database: samplesref
    tables:
      - name: trips